"use client";
import { useState } from "react";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Field, inputClass } from "@/components/ui/Field";
import { addMeasurement, calculateMeasurementArea, deleteMeasurement, JobIntelligenceError } from "@/lib/job-intelligence-repository";
import type { MeasurementType, WorkOrderMeasurement } from "@/lib/types";

const TYPES: { value: MeasurementType; label: string }[] = [
  ["linear_feet", "Linear feet"], ["width", "Width"], ["height", "Height"], ["area", "Area"], ["perimeter", "Perimeter"], ["count", "Count"], ["custom", "Custom"],
].map(([value, label]) => ({ value: value as MeasurementType, label }));

export function measurementTotal(item: WorkOrderMeasurement) { return item.width !== undefined && item.height !== undefined ? calculateMeasurementArea(item) : (item.value ?? 0) * item.quantity; }

export function WorkOrderMeasurements({ workOrderId, measurements }: { workOrderId: string; measurements: WorkOrderMeasurement[] }) {
  const [error, setError] = useState<string | null>(null);
  const total = measurements.reduce((sum, item) => sum + measurementTotal(item), 0);
  function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const number = (key: string) => { const value = String(data.get(key) ?? ""); return value === "" ? undefined : Number(value); }; try { addMeasurement(workOrderId, { type: String(data.get("type")) as MeasurementType, label: String(data.get("label")), value: number("value"), unit: String(data.get("unit")), width: number("width"), height: number("height"), quantity: number("quantity"), notes: String(data.get("notes")) }); form.reset(); setError(null); } catch (caught) { setError(caught instanceof JobIntelligenceError ? caught.message : "Unable to add measurement."); } }
  return <div className="grid gap-5 lg:grid-cols-3"><Card className="p-5 lg:col-span-1"><h2 className="font-semibold">Add measurement</h2><form onSubmit={submit} className="mt-4 space-y-3"><Field label="Type" htmlFor="type"><select id="type" name="type" className={inputClass}>{TYPES.map((type) => <option key={type.value} value={type.value}>{type.label}</option>)}</select></Field><Field label="Label" htmlFor="label"><input id="label" name="label" className={inputClass} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="Value" htmlFor="value"><input id="value" name="value" type="number" min="0" step="any" className={inputClass} /></Field><Field label="Unit" htmlFor="unit"><input id="unit" name="unit" placeholder="ft, in, sq ft" className={inputClass} /></Field><Field label="Width" htmlFor="width"><input id="width" name="width" type="number" min="0" step="any" className={inputClass} /></Field><Field label="Height" htmlFor="height"><input id="height" name="height" type="number" min="0" step="any" className={inputClass} /></Field><Field label="Quantity" htmlFor="quantity"><input id="quantity" name="quantity" type="number" min="0" step="any" defaultValue="1" className={inputClass} /></Field></div><Field label="Notes" htmlFor="measurementNotes"><textarea id="measurementNotes" name="notes" className={inputClass} /></Field>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<Button type="submit">Add Measurement</Button></form></Card><Card className="p-5 lg:col-span-2"><div className="flex justify-between"><h2 className="font-semibold">Measurements</h2><p className="text-sm font-semibold text-blue-700">Combined total: {total.toLocaleString()}</p></div>{measurements.length === 0 ? <p className="mt-6 text-sm text-slate-500">No measurements recorded.</p> : <ul className="mt-4 divide-y divide-slate-100">{measurements.map((item) => <li key={item.id} className="flex items-start justify-between gap-4 py-3"><div><p className="font-medium">{item.label}</p><p className="text-sm text-slate-500">{item.width !== undefined && item.height !== undefined ? `${item.width} × ${item.height} × ${item.quantity} = ${measurementTotal(item)} sq ft` : `${item.value ?? 0} ${item.unit} × ${item.quantity} = ${measurementTotal(item)}`}</p>{item.notes && <p className="mt-1 text-sm text-slate-600">{item.notes}</p>}</div><Button type="button" variant="secondary" onClick={() => deleteMeasurement(item.id)}>Delete</Button></li>)}</ul>}</Card></div>;
}
